"""Added incremental field

Revision ID: ebdbed01e9a7
Revises: 041d9a0f1159
Create Date: 2022-11-02 01:06:46.021902

"""

# revision identifiers, used by Alembic.
revision = 'ebdbed01e9a7'
down_revision = '041d9a0f1159'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_data', sa.Column('incremental', sa.Boolean(), nullable=True))
    op.add_column('queue_data', sa.Column('incremental', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
