name: image

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@main
        with:
          image-name: staffeln
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
          push: ${{ github.event_name != 'pull_request' }}
